<?php
/**
 * 功能简介
 *
 * 功能详细说明
 * @author: yanxs <541139655@qq.com>
 * @version: 1.0
 * @date: 2020/6/11
 */

namespace App\Services\Outer\Delivery;

use App\Exceptions\CommonException;
use App\Models\SaasExpress;
use App\Services\Outer\TbApi;
/**
 * Class BabyBus 宝宝巴士 物流信息回写
 * Created by sass.
 * Author: LJH
 * Date: 2020/6/11
 * Time: 17:56
 * @package App\Services\Outer\Delivery
 */
class BabyBus extends PartnerBase
{
    protected $url = '';

    public function deliveryReturn($orderNo,$deliveryCode,$deliveryName,$agent_id,$agent_code,$ext = null)
    {
        try{
            //根据物流简称查找物流信息
            $expressModel = app(SaasExpress::class);
            $express = $expressModel->where(['express_code'=>$deliveryName])->first();
            if(empty($express)){
                $err_data = [
                    'success'=>'false',
                    'err_msg'=>"找不到对应物流公司的信息"
                ];
                return $err_data;
            }
            //请求接口的数据封装
            $data = [
                'order_id'            => $orderNo,                  // 订单号
                'order_status'        => 2,                         // 订单状态;0：取消，1：生产中，2：已发货
                'shipping_no'         => $deliveryCode,             // 物流单号
                'shipping_code'       => $express['express_id'],    // 物流id
                'shipping_code_name'  => $deliveryName,             // 物流简称
                'shipping_name'       => $express['express_name'],  // 物流名称
            ];

            //生成签名
            $agentCodeList = config("common.agent_code");
            $data['hc_sig'] = $this->getSignature($data, $agentCodeList[$agent_code]['key']);

            //获取请求的url
            $url = $this->getUrl($orderNo);

            //请求接口回写物流信息
            $api = app(TbApi::class);
            $ret = $api->request($url.'?'.http_build_query($data),$data,'POST');

            //如果请求接口并回写成功
            if($ret['status']=='success' && empty($ret['error_code'])){
                $retData = [
                    'shipping'=>[
                        'is_success'=>true
                    ]
                ];
            }else{
                $err_data = [
                    'success'=>'false',
                    'err_msg'=>$ret['msg']
                ];
                return $err_data;
            }

            return ['success' => 'true', 'result' => $retData];

        }catch (CommonException $e){
            return ['success' => 'false','err_code'=>$e->getCode(),  'err_msg' => $e->getMessage()];
        }
    }



    protected function getUrl($orderNo)
    {
//        parent::getUrl($orderNo); // TODO: Change the autogenerated stub
        if (substr($orderNo, 0, 3) == '311') {
            $url = 'http://apikindergartending.babybus.com/Photos/FactoryNotice';
        } else {
            $url = 'https://apibb.babybus.com/Act/OrderNotice';
        }
        return $url;
    }
}