<?php
/**
 * 功能简介
 *
 * 功能详细说明
 * @author: yanxs <541139655@qq.com>
 * @version: 1.0
 * @date: 2020/6/11
 */

namespace App\Services\Outer\Delivery;


/**
 * Class KissBaby 亲宝宝 物流信息回写
 * Created by sass.
 * Author: LJH
 * Date: 2020/6/11
 * Time: 17:57
 * @package App\Services\Outer\Delivery
 */
class KissBaby extends PartnerBase
{
    protected $url = '';

    protected function getUrl($orderNo)
    {
//        parent::getUrl($orderNo); // TODO: Change the autogenerated stub
        $url = 'https://apierp.qbb6.com/mall/chrproduct/order/update';
        return $url;
    }
}