<!DOCTYPE html>
<html>
<head>
    <title>分销平台服务条款</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta charset="UTF-8" />
    <meta name="data-spm" content="a1zaa" />
    <meta http-equiv="Expires" content="0" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Cache-control" content="no-cache" />
    <meta http-equiv="Cache" content="no-cache" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{{URL::asset('css/agent/index/clause.css')}}">
</head>
<div class="agreementpreview agr-content">
    <h1 style="margin: 26px 0 0;text-align: center"><span style="font-size:21px;font-family:宋体,SimSun;color:black">分销平台网站服务条款</span></h1>
    <p style="text-indent: 377px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;版本： 2018年10月版</span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">前言</span></span></strong></p>
    <p style="line-height: 24px"><br /></p>
    <p style="line-height: 24px" data-spm-anchor-id="a1zaa.8161610.0.i2.1458cab8sXzhzB"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">欢迎访问分销平台网站并使用我们提供的产品和服务。</span></span></strong></p>
    <p style="line-height: 24px"><br /></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0" data-spm-anchor-id="a1zaa.8161610.0.i1.1458cab8sXzhzB">在 完成注册程序或以任何方式使用分销平台网站服务前，请您务必仔细阅读并透彻理解本分销平台网站服务条款(以下或简称“服务条款”)，在确认充分理解后选择接受 或不接受本服务条款；一旦您完成“同意条款并注册”或开始以其他方式使用分销平台服务，即表明您已阅读并同意受本服务条款的约束。如您不同意本服务条款或其 中任何条款约定，您应不再进行下一步或停止注册程序。</span></span></strong></p>
    <p style="line-height: 24px"><br /></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台再次提示您审慎阅读、充分理解各条款内容，特别是限制或免除责任的相应条款，限制或免除责任条款将以加粗或其他醒目形式提示您注意。</span></span></strong></p>
    <p style="line-height: 24px"><br /></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">如果您未满18周岁，请在法定监护人的陪同下阅读本服务条款。</span></span></strong></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">一、 签约主体以及协议范围</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">1.1.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台网站服务条款是您与分销平台计算有限公司（“分销平台”或者“我们”）就使用分销平台网站服务（包含为您提供网站页面信息浏览、账户注册服务等）而订立的有效合约。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">1.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">如您使用或购买分销平台网站上某一具体云服务，您可仍需确认具体服务对应的服务条款；请您审慎阅读、充分理解各条款内容，选择接受或不接受该服务条款。</span></span></strong></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">二、账户的注册、使用与安全</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.1. </span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">注册的资格</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.1.1. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您确认，在您完成注册程序或以其他分销平台允许的方式实际使用本服务时，您应当是具备完全民事权利能力和完全民事行为能力的自然人</span><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">、法人或其他组织（以下或简称为“您”）。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.1.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">若您是未成年人或限制民事行为能力人，则您不具备前述主体资格，您及您的监护人应承担因您的不当注册行为而导致的一切后果。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.1.3. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您还需确保您不是任何国家、国际组织或者地域实施的贸易限制、制裁或其他法律、规则限制的对象，否则您可能无法正常注册及使用分销平台服务。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.2. </span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">账户注册</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">2.2.1.</span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">当您按照注册页面提示填写信息、阅读并同意本服务条款且完成全部注册程序后，您可获得分销平台账户并成为分销平台的用户。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.2.2. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您在注册时候设置或确认的账户名（“账户名称”）及您设置的密码，将在注册成功后成为您的账户</span><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">（账户名称及密码合称“账户”）。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">2.2.3. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">您设置的账户名不得违反国家法律法规、分销平台的管理规范或容易引起您与分销平台身份的混淆，否则您的账户可能不能注册成功或分销平台有权经通知您后予以注销。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.2.4. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您应当按照法律法规要求或按相应页面的提示，准确提供并及时更新您的账户信息，以使之真实、及时、完整和准确。如您提供的资料错误、不实、过时或不完整的，分销平台可以向您发出询问及/或要求改正的通知，您应按照分销平台的要求配合提供或者更新相关资料。<strong><span style="text-decoration:underline;">因您填写的信息、资料不真实、不及时、不完整或不准确的，您应承担您不能使用分销平台账户（不能注册成功、或账户被冻结、注销）或您在使用过程中的后果和损失。</span></strong></span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">2.2.5. </span></strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">分销平台可能会就某些产品或服务的开通，要求您提供更多的身份资料和信息，做进一步的身份认证或资格验证，您的账户只有在通过这些认证和验证之后，方可获得使用相关产品或服务的资格。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">2.2.6. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">通 常情况下，您的分销平台账户是您在分销平台网站进行一切活动的唯一身份标识，除非另有约定，每一个分销平台账户都可以在本网站独立开展活动。但在下列情形下，阿 里云有权根据自己的判断，对同一及/或关联法律主体拥有的多个分销平台账户进行统一处理，如根据不同分销平台账户在注册、登录、使用中的关联信息，分销平台判断 其实际为同一用户。关联信息举例：同一证件、同一手机号、同一支付账号、同一设备、同一地址等。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3. </span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">账户的使用和安全</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3.1.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您有权使用您设定的账户</span><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">登录分销平台网站，进而使用分销平台提供的其他服务。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3.2. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台可能会以<strong>邮件、站内信、短信或电话等方式</strong>通知您服务进展情况以及提示您进行下一步的操作。在服务过程中您应当及时登录到分销平台账户查看和进行交易操作。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3.3. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">一个分销平台账户仅能对应唯一的法律主体。除非有法律明文规定、司法裁定或者经分销平台同意的情况下，您不得以任何方式转让、赠与或让他人继承您的分销平台账户。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3.4. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您的账户和密码由您自行设置并由您保管，您须对您的分销平台账户和密码保密。您需确保您在每个上网时段结束时，以正确步骤离开网站。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3.5. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">如发现他人未经授权使用您的分销平台账户和密码，您应立即通知分销平台；分销平台将协助您冻结账户、更改密码或进行其他安全设置；您理解分销平台对您的请求采取行动需要合理时间，分销平台对在采取行动前已经产生的以及由您引发的后果（包括但不限于您的任何损失）不承担任何责任。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">2.3.6. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台亦会在网站服务端采取合理的技术措施保障账户的安全。</span></p>
    <p style="margin: 5px 0"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></strong></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">三、账户的冻结、注销及申诉</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1. </span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">账户的冻结</span></strong></p>
    <p style="text-indent: 32px;line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您的分销平台账户（全部或部分权限或功能）在如下情况可能被冻结（如分销平台帐户被限制资金转出功能等）</span></span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">，分销平台将通过邮件、站内信、短信或电话等方式通知您：</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.1. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">基 于分销平台网站或服务运行和交易安全的需要，如您发生或可能发生破坏或试图破坏分销平台或分销平台关联公司公平交易环境或正常交易秩序的，或任何使用含有分销平台 或分销平台关联公司名称、品牌且对他人有误导嫌疑或任何使用某种中英文(全称或简称)、数字、域名等意图表示或映射与分销平台或其关联公司具有某种关联的；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">违反本服务条款、分销平台网站的相关规则、规范（如交易规则、管理规范）、服务说明以及其他服务协议/条款的；</span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0"> </span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.3. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">违反国家法律、法规、政策、法律文书的规定的；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.4. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您遭到他人投诉， 且对方已经提供了相关证据的，而您未按照我们的要求提供相反证据的；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.5. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台根据合理分析判断您的账户操作、</span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">收益、兑换等存在异常的；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.6. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">国家有权机关要求进行的冻结的；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.1.7. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台合理判断，您发生与如上行为性质相同或产生如上类似风险的其他情况的。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.2. </span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">账户的注销</span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;">3.2.1. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;">如果出现如上第3.1条情形且情形严重的，或基于国家有权机关的要求，<span style="border:none windowtext 1px;padding:0">您的分销平台账户（全部或部分权限或功能）将被注销，分销平台将通过邮件、站内信、短信或电话等方式通知您。</span></span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.2.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您理解并同意，如您连续</span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">12</span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">个月未通过账户登录过分销平台网站，且您的账户下不存在任何未到期的服务，分销平台有权注销您的账户，您将不能再登录分销平台网站。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">3.3. </span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">申诉</span></strong></p>
    <p style="text-indent: 32px;line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">发生前述账户冻结或注销情况下，您应及时予以关注并可以按照程序进行申诉等后续操作：</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">3.3.1. </span></strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">您通过申诉程序，向分销平台申请解除上述冻结或注销的，为了您的账户安全，您应配合如实提供身份证明及相关资料，以及分销平台要求的其他信息或文件，以便分销平台进行核实。您应充分理解您的申诉并不必然被允许，分销平台有权决定是否同意您的申诉请求<strong>。</strong></span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">3.3.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">您理解并同意，如果您拒绝如实提供身份证明及相关资料，或未能通过分销平台审核，分销平台有权长期冻结该等账户且长期限制账户部分或全部功能。</span></span></strong></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">四、网站服务及规范</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">4.1</span></strong><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">．</span></strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">您有权享受分销平台通过本网站提供的互联网技术服务和信息服务。您同时还应根据本服务条款以及您在购买具体服务时确认的相关条款和条件，履行及时付款、服务管理等责任。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">4.2. </span></strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">您使用分销平台的服务，您应保证：</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">4.2.1. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您使用分销平台服务时将遵从国家、地方法律法规、行业惯例和社会公共道德，不会利用分销平台提供的服务进行存储、发布、传播如下信息和内容：</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅰ）违反国家法律法规政策的任何内容（信息）；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅱ）违反国家规定的政治宣传和/或新闻信息；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅲ）涉及国家秘密和/或安全的信息；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅳ）封建迷信和/或淫秽、色情、下流的信息或教唆犯罪的信息；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅴ）博彩有奖、赌博游戏；违反国家民族和宗教政策的信息；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅵ）妨碍互联网运行安全的信息；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅶ）侵害他人合法权益的信息和/或其他有损于社会秩序、社会治安、公共道德的信息或内容；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">（ⅷ）您同时承诺不得为他人发布上述不符合国家规定和/或本服务条款约定的信息内容提供任何便利，包括但不限于设置URL、BANNER链接等；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">4.2.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">不应出现任何破坏或试图破坏网络安全等的行为，包括不会利用技术或其他手段破坏或扰乱本网站及分销平台其他客户的网站；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">4.2.3. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您使用分销平台网站的服务应符合本服务条款；</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">如您违反上述保证，分销平台除有权根据相关服务条款采取删除信息、中止服务、终止服务的措施，并有权冻结或注销您账户部分或全部功能。</span></span></strong></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">五、隐私及个人信息的保护</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">&nbsp;&nbsp;</span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">您的信任对分销平台非常重要，分销平台深知用户信息安全的重要性，分销平台将按照法律法规要求，采取安全保护措施，保护您的用户信息安全可控。具体详见《</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border:none windowtext 1px;padding:0">&nbsp;</span></strong></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">六、知识产权</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">6.1. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">我们尊重知识产权，除非获得了您的同意，分销平台不会擅自使用、修改、复制、公开传播、改变、散布、发行或公开发表您拥有知识产权的成果。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">6.2. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">任何组织或个人认为分销平台网站的网页内容，如转载文章、云市场服务商发布的商品信息等可能侵犯其合法权益的，可向分销平台提出书面权利通知，分销平台将在收到知识产权权利人合格通知后依法尽快处理。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">6.3.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">除非另行说明，分销平台网站Logo、“分销平台”等文字、图形及其组合，以及分销平台网站的其他标识、徽记、分销平台服务的名称、技术文档等的知识产权为分销平台及其关联公司所有。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">6.4. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您应尊重分销平台和第三方的知识产权和其他合法权利/权益，并保证在发生侵犯前述权益的违法事件时，保护分销平台及其雇员、股东、合作伙伴等免于因该等事件受到影响或损失，分销平台保留在您侵犯分销平台及/或其他第三方的合法权利/权益时终止向您提供服务并不退还任何款项的权利</span></span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">。</span></strong></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">其他具体信息详见《<a href="http://terms.aliyun.com/legal-agreement/terms/suit_bu1_ali_cloud/suit_bu1_ali_cloud201710161525_98396.html?spm=5176.8142029.631162.law.3836dbccuy7W0b">法律声明及隐私权政策</a>》的法律声明部分。</span></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">七、保密</span></strong></p>
    <p style="text-indent: 0px; margin-bottom: 10px; line-height: 24px;"><span style="font-family: 宋体, SimSun; text-indent: 32px;"><b>&nbsp; </b>分销平台承诺对您注册账户时或使用分销平台服务时提交或知悉的信息采取保密措施，不向第三方披露您的信息，除非：</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">7.1.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">依据本服务条款或者您与分销平台之间其他服务协议、合同、在线条款等规定可以提供的；</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">7.2. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">依据法律法规的规定或行政、司法等职权部门要求应当提供的；</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">7.3.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">在不违反本服务条款约定责任的前提下，该保密信息已经公开或能从公开领域获得。</span></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">八、责任范围和责任限制</span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">8.1. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您了解并同意，您应承担因您使用本服务、违反本服务条款或在您的账户下采取的任何行动而导致的任何第三方索赔。如果由此引起分销平台及其关联公司、员工、客户和合作伙伴被第三方索赔的，您应负责处理，并赔偿分销平台及其关联公司由此遭受的全部损失和责任。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;">8.2. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">在适用法律许可的范围内，分销平台不对与本服务条款有关或由本服务条款引起的任何间接的、惩罚性的、特殊的、派生的损失承担赔偿责任。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">8.3. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台在此提示，您在使用分销平台服务期间应当遵守中华人民共和国的法律，不得危害网络安全，不得利用分销平台的服务从事侵犯他人名誉、隐私、知识产权和其他合法权益的活动。分销平台不对您使用分销平台服务的违法或违约行为承担任何责任。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">8.4.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台用户在分销平台网站的论坛、社区以及云市场上自行上传、提供、发布相关信息，包括但不限于用户名称、公司名称、 联系人及联络信息，相关图片、资讯等，均由用户自行提供，分销平台的用户须对其提供的前述信息依法承担全部责任。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">8.5.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">如果您通过使用分销平台网站或获取来自第三方的任何产品或服务，例如，分销平台云市场上的服务商依托云市场向您提供服务，服务商将对其提供的服务向您负责，分销平台对此第三方服务不承担任何责任。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">8.6. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">在 某些情况下，为了帮助您更便捷的使用分销平台的服务，分销平台可能会展示分销平台的参考代码或软件（如属于第三方开源软件，您则应遵守第三方开源软件的相关使用 要求），基于相应展示页面的使用说明，该等软件可能允许您予以下载、进行二次开发等相关操作，您应理解并承诺，该等代码的知识产权属于分销平台，您在使用时 应明确表明权利人，同时，分销平台不对您能否使用以及使用该等代码、软件的工作和后果负责。</span></span></strong></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">九、不可抗力和意外事件</span></strong></p>
    <p style="text-indent: 0px; margin-bottom: 10px; line-height: 24px;"><span style="font-family: 宋体, SimSun; text-indent: 32px;"><b>&nbsp; &nbsp;</b>分销平台的网站可能因为下列不可抗力或意外事件无法正常运行的，分销平台不承担损害赔偿责任：</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">9.1. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">因自然灾害、罢工、暴乱、战争、政府行为、司法行政命令等不可抗力因素；</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">9.2.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">因电力供</span><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">应故障、通讯网络故障等公共服务因素；</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">9.3. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">经提前公告或通知的，分销平台在短时间内的系统维护。</span></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">十、通知送达</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">11.1.</span></strong> <span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">您理解并同意，分销平台可通过网页公告、电子邮件、站内信、短信、电话、系统消息以及即时通信等以上一种或多种通知方式向您发送通知，且分销平台可以信赖您所提供的联系信息是完整、准确且当前有效的；上述通知在发送成功后视为已送达。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">11.2</span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">．</span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">除非本服务条款另有约定或分销平台与您另行签订的协议明确规定了通知方式，您发送给分销平台的通知，应当通过分销平台对外正式公布的通信地址、传真号码、电子邮件地址等联系信息进行送达。</span></p>
    <p style="line-height: 24px"><span style="font-family:宋体,SimSun;">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">十一、条款的更新和终止</span></strong></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">12.1. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台有权对本服务条款及相应的服务规则内容进行变更，并将网页公告、电子邮件、站内信、短信等方式予以公告或通知；若您在本服务条款内容变更后继续使用本服务的，表示您已充分阅读、理解并接受修改后的内容，也将遵循修改后的条款内容</span></span></strong><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">。</span></strong></p>
    <p style="line-height:24px"><strong><span style="font-family:宋体,SimSun;">12.2.</span></strong> <span style="font-family:宋体,SimSun;">在您的账户注销或经双方协商一致终止网站服务的，本服务条款终止。</span></p>
    <p style="line-height:24px"><span style="font-family:宋体,SimSun;">&nbsp;</span></p>
    <p style="margin-bottom: 10px;line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">十二、其他</span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">13.1. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">本服务条款由本服务条款的内容、网站相关页面上展现的规则、规范，服务说明（含操作文档）和您点击确认的其他条款/条件组成，分销平台和您均受其约束，且其中的相关名词可相互引用、解释。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">13.2. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">本服务条款的章节标题仅为行文方便而设，不具有法律或合同效力。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">13.3. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">本服务条款任一条款被视为废止、无效或不可执行，该条款应视为可分的且不影响本服务条款及其他条款的有效性及可执行性。</span></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">13.4. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">分销平台有权在分销平台官网上发布公告、发站内通知或邮件通知等方式将本服务的权利义务全部或者部分转移给分销平台的关联公司。</span></p>
    <p style="line-height: 24px"><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">13.5. </span></span></strong><strong><span style="text-decoration:underline;"><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">除另有约定外，出于服务专业性考虑，分销平台亦可能委托关联公司或其他法律主体向您提供分销平台网站上一项或多项具体服务，同时您可能会与该等公司订立相关条款或条件，请您审慎阅读、充分理解条款和条件内容，选择接受或不接受该条款和条件。</span></span></strong></p>
    <p style="line-height: 24px"><strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">13.6. </span></strong><span style="font-family:宋体,SimSun;border: 1px none windowtext;padding: 0">本服务条款项下之保密条款、知识产权条款、法律适用与管辖条款以及性质上理应存续的其他条款（如对注册信息的真实性保证等），不因本条款的终止而失效。</span></p>
    <p style="line-height:24px"><span style="font-family:宋体,SimSun;">&nbsp;</span></p>
    <p style="line-height:24px"><span style="font-family:宋体,SimSun;">&nbsp;</span></p>
    <p><br /></p>
</div>
<div id="App">
    <div data-reactid=".0">
        <div data-reactid=".0.0">
            <noscript data-reactid=".0.0.0"></noscript>
            <span class="hide" title="目录导航" data-reactid=".0.0.1"></span>
            <b class="hide" data-reactid=".0.0.2"><i class="top-arrow1" data-reactid=".0.0.2.0"></i><i class="top-arrow2" data-reactid=".0.0.2.1"></i></b>
            <div class="hide" data-reactid=".0.0.3">
                <div class="menu-tree-l hide" data-reactid=".0.0.3.0">
                    <span data-reactid=".0.0.3.0.0"></span>
                    <ul data-reactid=".0.0.3.0.1"></ul>
                    <span data-reactid=".0.0.3.0.2"></span>
                </div>
                <div class="menu-tree-r" data-reactid=".0.0.3.1">
                    <ul data-reactid=".0.0.3.1.0"></ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="display:none;" id="remindContentDiv"></div>
<input id="revisionNum" value="1" type="hidden" />
<input id="needRemind" value="n" type="hidden" />
<input id="agreementId" value="875" type="hidden" />
<iframe style="width: 0px; height: 0px; display: none;" src="%E9%98%BF%E9%87%8C%E4%BA%91%E7%BD%91%E7%AB%99%E6%9C%8D%E5%8A%A1%E6%9D%A1%E6%AC%BE201712%E6%9C%88%E7%89%88_files/blk.html" id="_oid_ifr_"></iframe>
</body>
</html>