<?php
namespace App\Services\Outer\Erp;

use App\Services\Outer\AbstractApi;


/**
 * 请求工厂erp相关的api
 *
 * 请求工厂erp相关的api
 * @author: yanxs <541139655@qq.com>
 * @version: 1.0
 * @date: 2019/12/25
 */
class Api extends AbstractApi
{
    protected $isSign = true;
    protected $secretKey = "odoo"; //生成签名的key

    /**
     * @param \App\Services\Outer\请求地址 $url
     * @param \App\Services\Outer\请求参数 $params
     * @param string $method
     * @return mixed
     */
    public function request($url, $params, $method = 'POST')
    {
        return parent::request($url, $params, $method); // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     * @param string $secretKey
     * @return string
     */
    protected function getSign($params, $secretKey = '')
    {
        ksort($params);

        $ret_str = '';
        foreach ($params as $k=>$v) {
            $ret_str .= $k.'='.$v."&";
        }
        $ret_str = $ret_str.'key='.$secretKey;
        return strtoupper(md5($ret_str));
    }
}