<?php
namespace App\Repositories;
use App\Models\SaasCustomerLevel;
use App\Models\SaasSalesChanel;
use App\Services\Helper;

/**
 * 营销渠道仓库模板
 * 营销渠道仓库模板
 * @author: hlt <vali12138@163.com>
 * @version: 1.0
 * @date:  2020/04/07
 */
class SaasSalesChanelRepository extends BaseRepository
{

    public function __construct(SaasSalesChanel $model)
    {
        $this->model = $model;
    }

    public function getList($where=[], $order='created_at', $sort = "desc")
    {
        return parent::getList($where, $order, $sort); // TODO: Change the autogenerated stub
    }

    //获取渠道名称
    public function getChanleName($id)
    {
        $name = $this->model->where(['cha_id' => $id])->value('cha_name');
        return $name;

    }


    //获取渠道
    public function getSalesChanel($cha_flag)
    {
        $chaList = $this->model->where(['cha_flag'=>$cha_flag])->get()->toArray();
        $chaList = Helper::ListToKV('cha_id','cha_name',$chaList);
        $chaList = Helper::getChooseSelectData($chaList);
        return $chaList;
    }

    //获取渠道与用户列表
    public function getCustomerChannleList($mid)
    {

        $chaList = $this->getList()->toArray();
        $custLevel = app(SaasCustomerLevel::class);
        foreach ($chaList as $k=>$v)
        {
            $customerArr = $custLevel->where(['cust_lv_type' => $v['cha_flag'],'mch_id' => $mid])->get()->toArray();
            $chaList[$k]['customerList'] = $customerArr;
        }
        return $chaList;
    }

    //获取分销商渠道id
    public function getAgentChannleId()
    {
        $cha_id = $this->model->where(['short_name' => AGENT_CHANNEL])->value('cha_id');
        return $cha_id;
    }
    //获取官网渠道id
    public function getOfficalChannleId()
    {
        $cha_id = $this->model->where(['short_name' => OFFICAL_CHANNEL])->value('cha_id');
        return $cha_id;
    }
    //获取桌面软件渠道id
    public function getDesktopChannleId()
    {
        $cha_id = $this->model->where(['short_name' => DESKTOP_CHANNEL])->value('cha_id');
        return $cha_id;
    }
    //获取微商城渠道id
    public function getWxChannleId()
    {
        $cha_id = $this->model->where(['short_name' => WX_CHANNEL])->value('cha_id');
        return $cha_id;
    }
    //获取小程序渠道id
    public function getMinAppChannleId()
    {
        $cha_id = $this->model->where(['short_name' => MINAPP_CHANNEL])->value('cha_id');
        return $cha_id;
    }
}

