<?php
namespace App\Repositories;
use App\Models\SaasProductsChanle ;
use App\Models\SaasSalesChanel;

/**
 * 商品销售渠道仓库模板
 * 商品销售渠道仓库模板
 * @author: hlt <vali12138@163.com>
 * @version: 1.0
 * @date:  2020/04/07
 */
class SaasProductsChanleRepository extends BaseRepository
{

    public function __construct(SaasProductsChanle $model)
    {
        $this->model = $model;
    }

    public function getList($where=[], $order='created_at', $sort = "desc")
    {
        return parent::getList($where, $order, $sort); // TODO: Change the autogenerated stub
    }
    //获取商品的销售渠道
    public function getProductChannle($prodId, $mid = PUBLIC_CMS_MCH_ID)
    {
        $array = $this->model->where(['prod_id' => $prodId,'mch_id' => $mid])->get()->toArray();
        return $array;
    }
    //获取商品的销售渠道与渠道名
    public function getProductChannleDetail($prodId, $mid = PUBLIC_CMS_MCH_ID)
    {
        if (!is_array($prodId)){
         $prodId = explode(',',$prodId);
        }
        $array = $this->model
            ->leftJoin('saas_sales_chanel', 'saas_products_chanle.cha_id', '=', 'saas_sales_chanel.cha_id')
            ->whereIn('prod_id',$prodId)
            ->where(['mch_id' => $mid])
            ->select('saas_products_chanle.*','saas_sales_chanel.cha_name')
            ->get()->toArray();
        $return=[];
        foreach ($array as $k =>$v)
        {
                $return[$v['prod_id']][$v['cha_id']] = $v['cha_name'];
        }
        return $return;
    }


}

