<?php
namespace App\Repositories;
use App\Models\SaasProdSuppliers ;

/**
 * 商品销售渠道仓库模板
 * 商品销售渠道仓库模板
 * @author: hlt <vali12138@163.com>
 * @version: 1.0
 * @date:  2020/04/07
 */
class SaasProductsSuppliersRepository extends BaseRepository
{

    public function __construct(SaasProdSuppliers $model)
    {
        $this->model = $model;
    }

    public function getList($where=[], $order='created_at', $sort = "desc")
    {
        return parent::getList($where, $order, $sort); // TODO: Change the autogenerated stub
    }
    //获取商品的销售渠道
    public function getProductSupplier($prodId, $mid = PUBLIC_CMS_MCH_ID)
    {
        $array = $this->model->where(['prod_id' => $prodId])->get()->toArray();
        return $array;
    }


}

