<?php
namespace App\Repositories;

use App\Models\SaasSkuToCustlevelPrice;

/**
 * 客户定价仓库
 *
 * 客户定价仓库
 * @author: yanxs <541139655@qq.com>
 * @version: 1.0
 * @date: 2020/4/22
 */
class SaasSkuToCustlevelPriceRepository extends BaseRepository
{
    public function __construct(SaasSkuToCustlevelPrice $model)
    {
        $this->model = $model;
    }

    public function getList($where=[], $order='created_at', $sort = "desc")
    {
        return parent::getList($where, $order, $sort); // TODO: Change the autogenerated stub
    }


}