<?php
namespace App\Repositories;
use App\Models\SaasProductsMedia ;

/**
 * 商品图片仓库模板
 * 商品图片仓库模板
 * @author: hlt <vali12138@163.com>
 * @version: 1.0
 * @date:  2020/04/07
 */
class SaasProductsMediaRepository extends BaseRepository
{

    public function __construct(SaasProductsMedia $model)
    {
        $this->model = $model;
    }

    public function getList($where=[], $order='created_at', $sort = "desc")
    {
        return parent::getList($where, $order, $sort); // TODO: Change the autogenerated stub
    }
    //获取商品的照片
    public function getProductPhoto($prodId)
    {
        $array = $this->model->where(['prod_id' => $prodId])->orderBy('sort','asc')->get()->toArray();
        return $array;
    }
    //删除媒体表中的商品图片
    public function delProductsPhoto($prodId)
    {
        $this->model->where(['prod_id' => $prodId])->delete();
    }

}

